version: '3'
services:
  db:
    build:
      context: ./postgres
      dockerfile: Dockerfile
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "testdb"
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --locale=ja_JP.UTF-8"
    ports:
      - 5432:5432
    volumes:
      - ./postgres/init_sql://docker-entrypoint-initdb.d/
      - test-pgdata://var/lib/postgresql/data

  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    image: nodeapp
    container_name: nodeapp
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/testdb
    tty: true
    ports:
      - 3000:3000
    volumes:
      - ./app://home/app
    depends_on:
      - db

volumes:
  test-pgdata:
    external: true